name: xtensor-fftw
channels:
  - QuantStack
  - conda-forge
dependencies:
  - xtensor
  - xtensor-io ==0.4.0
  - boost ==1.66.0
  - boost-cpp ==1.66.0
  - xeus-cling ==0.4.2
  - xtensor-fftw >= 0.2.4
  - notebook
  - widgetsnbextension
  - nbstripout
